// =============================================================================
// Author: Vladyslav Zaiets | https://sarmkadan.com
// CTO & Software Architect
// =============================================================================

using System.Net.Mime;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.Extensions.Options;

namespace ApiKeyGateway.Middleware;

/// <summary>
/// Factory for creating RFC 7807 ProblemDetails responses.
/// Implements the ProblemDetails format as specified in RFC 7807 for standardized error responses.
/// </summary>
/// <remarks>
/// RFC 7807 defines a standardized format for HTTP API error responses:
/// - type: A URI reference that identifies the problem type (SHOULD be dereferenceable)
/// - title: A short, human-readable summary of the problem type
/// - status: The HTTP status code generated by the origin server
/// - detail: A human-readable explanation specific to this occurrence of the problem
/// - instance: A URI reference that identifies the specific occurrence of the problem
/// </remarks>
public static class GatewayProblemDetailsFactory
{
    /// <summary>
    /// Creates a ProblemDetails response for invalid API key errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="message">The error detail message.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateInvalidKeyProblem(
        HttpContext context,
        string message,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentException.ThrowIfNullOrWhiteSpace(message);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:invalid-key",
            Title = "Invalid API Key",
            Status = StatusCodes.Status401Unauthorized,
            Detail = message,
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for API key expired errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateKeyExpiredProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:key-expired",
            Title = "API Key Expired",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "The API key has expired and is no longer valid",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for disabled API key errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateKeyDisabledProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:key-disabled",
            Title = "API Key Disabled",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "The API key has been disabled",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for IP not whitelisted errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateIpNotWhitelistedProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:ip-not-whitelisted",
            Title = "IP Address Not Whitelisted",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "The requesting IP address is not whitelisted for this API key",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for missing API key errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateMissingKeyProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:missing-api-key",
            Title = "Missing API Key",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "X-API-Key header is required",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for invalid API key format errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateInvalidKeyFormatProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:invalid-key-format",
            Title = "Invalid API Key Format",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "The API key format is invalid",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for API key not found errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateKeyNotFoundProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:key-not-found",
            Title = "API Key Not Found",
            Status = StatusCodes.Status401Unauthorized,
            Detail = "The specified API key does not exist",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for route scope restriction errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateRouteScopeRestrictedProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:route-scope-restricted",
            Title = "Route Scope Restricted",
            Status = StatusCodes.Status403Forbidden,
            Detail = "The API key does not have permission to access this route",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for usage quota exceeded errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="quotaResetAt">When the quota resets.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateQuotaExceededProblem(
        HttpContext context,
        DateTime quotaResetAt,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:quota-exceeded",
            Title = "Usage Quota Exceeded",
            Status = StatusCodes.Status429TooManyRequests,
            Detail = "Usage quota exceeded for this period",
            Instance = instance ?? context.Request.Path.ToString(),
            Extensions = { ["quotaResetAt"] = quotaResetAt }
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for rate limit exceeded errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="retryAfter">When to retry the request.</param>
    /// <param name="limit">The rate limit that was exceeded.</param>
    /// <param name="windowInSeconds">The time window in seconds.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateRateLimitExceededProblem(
        HttpContext context,
        DateTime retryAfter,
        int limit,
        int windowInSeconds,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:rate-limited",
            Title = "Rate Limit Exceeded",
            Status = StatusCodes.Status429TooManyRequests,
            Detail = string.Format(Domain.Constants.ErrorMessages.RateLimitExceeded, limit, GetTimeUnit(windowInSeconds)),
            Instance = instance ?? context.Request.Path.ToString(),
            Extensions =
            {
                ["limit"] = limit,
                ["windowInSeconds"] = windowInSeconds,
                ["retryAfter"] = retryAfter
            }
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for unsupported media type errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateUnsupportedMediaTypeProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:unsupported-media-type",
            Title = "Unsupported Media Type",
            Status = StatusCodes.Status415UnsupportedMediaType,
            Detail = "Content-Type must be application/json",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for payload too large errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="maxSizeBytes">The maximum allowed size.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreatePayloadTooLargeProblem(
        HttpContext context,
        long maxSizeBytes,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:payload-too-large",
            Title = "Payload Too Large",
            Status = StatusCodes.Status413PayloadTooLarge,
            Detail = $"Request body must be smaller than {maxSizeBytes} bytes",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for missing API key header errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateMissingKeyHeaderProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:missing-api-key-header",
            Title = "Missing API Key Header",
            Status = StatusCodes.Status400BadRequest,
            Detail = "X-API-Key header is required",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for service unavailable errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="retryAfterSeconds">Seconds to wait before retrying.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateServiceUnavailableProblem(
        HttpContext context,
        int retryAfterSeconds = 30,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:service-unavailable",
            Title = "Service Unavailable",
            Status = StatusCodes.Status503ServiceUnavailable,
            Detail = "Authentication service temporarily unavailable. Please retry.",
            Instance = instance ?? context.Request.Path.ToString(),
            Extensions = { ["retryAfter"] = retryAfterSeconds }
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for unauthorized access errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateUnauthorizedAccessProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:unauthorized-access",
            Title = "Unauthorized Access",
            Status = StatusCodes.Status403Forbidden,
            Detail = "Access to this resource is forbidden",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Creates a ProblemDetails response for internal server errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateInternalServerErrorProblem(
        HttpContext context,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:internal-server-error",
            Title = "Internal Server Error",
            Status = StatusCodes.Status500InternalServerError,
            Detail = "An unexpected error occurred",
            Instance = instance ?? context.Request.Path.ToString()
        };
    }

    /// <summary>
    /// Gets the time unit description for rate limit error messages.
    /// </summary>
    private static string GetTimeUnit(int seconds) => seconds switch
    {
        1 => "second",
        60 => "minute",
        3600 => "hour",
        86400 => "day",
        _ => $"{seconds} seconds"
    };

    /// <summary>
    /// Writes a ProblemDetails response to the HTTP context with proper content type.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="problemDetails">The ProblemDetails to write.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    public static async Task WriteProblemAsync(this HttpContext context, ProblemDetails problemDetails)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(problemDetails);

        context.Response.ContentType = MediaTypeNames.Application.ProblemJson;
        context.Response.StatusCode = problemDetails.Status ?? StatusCodes.Status500InternalServerError;

        // Set Retry-After header for 429 responses
        if (problemDetails.Status == StatusCodes.Status429TooManyRequests &&
            problemDetails.Extensions.TryGetValue("retryAfter", out var retryAfter))
        {
            if (retryAfter is int retryAfterInt)
            {
                context.Response.Headers.RetryAfter = retryAfterInt.ToString();
            }
            else if (retryAfter is DateTime retryAfterDate)
            {
                var seconds = (int)(retryAfterDate - DateTime.UtcNow).TotalSeconds;
                context.Response.Headers.RetryAfter = seconds.ToString();
            }
        }

        await context.Response.WriteAsJsonAsync(problemDetails);
    }

    /// <summary>
    /// Creates a ProblemDetails response for transformation blocked errors.
    /// </summary>
    /// <param name="context">The HTTP context.</param>
    /// <param name="blockReason">The reason the request was blocked.</param>
    /// <param name="instance">The request URI that caused the error.</param>
    /// <returns>A ProblemDetails object ready for serialization.</returns>
    public static ProblemDetails CreateTransformationBlockedProblem(
        HttpContext context,
        string blockReason,
        string? instance = null)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentException.ThrowIfNullOrWhiteSpace(blockReason);

        return new ProblemDetails
        {
            Type = "urn:api-key-gateway:transformation-blocked",
            Title = "Transformation Blocked",
            Status = StatusCodes.Status403Forbidden,
            Detail = blockReason,
            Instance = instance ?? context.Request.Path.ToString()
        };
    }
}